package com.codereviewagent.api.controller;

import com.codereviewagent.api.model.UserAccount;
import com.codereviewagent.api.repository.UserRepository;
import com.codereviewagent.api.service.RuleService;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

import org.springframework.http.HttpStatus;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContext;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.web.context.HttpSessionSecurityContextRepository;
import org.springframework.security.web.csrf.CsrfToken;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

import java.security.Principal;
import java.util.Map;
import java.util.UUID;

/** Exposes registration, session login, current-user, and CSRF endpoints. */
@RestController
@RequestMapping("/api/v1/auth")
public class AuthController {
    /**
     * Credentials accepted by registration and login; validation is also enforced server-side.
     *
     * @param username normalized account name, between 3 and 80 characters
     * @param password account password, between 6 and 128 characters
     */
    public record Credentials(
            @NotBlank @Size(min = 3, max = 80) String username,
            @NotBlank @Size(min = 6, max = 128) String password) {}

    private final UserRepository users;
    private final PasswordEncoder encoder;
    private final AuthenticationManager authenticationManager;
    private final HttpSessionSecurityContextRepository contextRepository;
    private final RuleService rules;

    /**
     * Creates the authentication controller with session and account collaborators.
     *
     * @param users account repository
     * @param encoder password hash encoder
     * @param authenticationManager Spring Security authentication manager
     * @param contextRepository session security-context repository
     * @param rules service used to create default rules for new accounts
     */
    public AuthController(
            UserRepository users,
            PasswordEncoder encoder,
            AuthenticationManager authenticationManager,
            HttpSessionSecurityContextRepository contextRepository,
            RuleService rules) {
        this.users = users;
        this.encoder = encoder;
        this.authenticationManager = authenticationManager;
        this.contextRepository = contextRepository;
        this.rules = rules;
    }

    /**
     * Returns the CSRF token required for state-changing requests.
     *
     * @param token request-scoped CSRF token generated by Spring Security
     * @return response containing the token value
     */
    @GetMapping("/csrf")
    public Map<String, String> csrf(@RequestAttribute("_csrf") CsrfToken token) {
        return Map.of("token", token.getToken());
    }

    /**
     * Validates and creates a normalized user account with default rules.
     *
     * @param request validated registration credentials
     * @return response containing the normalized username
     * @throws ResponseStatusException with 400 for invalid input or 409 for duplicate usernames
     */
    @PostMapping("/register")
    @ResponseStatus(HttpStatus.CREATED)
    public Map<String, String> register(@Valid @RequestBody Credentials request) {
        String username = request.username().trim().toLowerCase(java.util.Locale.ROOT);
        if (!username.matches("[a-z0-9_.-]{3,80}")) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Invalid username");
        }
        if (users.existsByUsername(username)) {
            throw new ResponseStatusException(HttpStatus.CONFLICT, "Username already exists");
        }
        UserAccount user =
                users.save(
                        new UserAccount(
                                UUID.randomUUID().toString(),
                                username,
                                encoder.encode(request.password())));
        rules.createDefaults(user.id);
        return Map.of("username", username);
    }

    /**
     * Authenticates credentials and persists the authenticated session context.
     *
     * @param request validated login credentials
     * @param servletRequest current HTTP request used to create and rotate the session
     * @param servletResponse current HTTP response used to persist the security context
     * @return response containing the authenticated username
     */
    @PostMapping("/login")
    public Map<String, String> login(
            @Valid @RequestBody Credentials request,
            HttpServletRequest servletRequest,
            HttpServletResponse servletResponse) {
        Authentication authentication =
                authenticationManager.authenticate(
                        new UsernamePasswordAuthenticationToken(
                                request.username().trim().toLowerCase(java.util.Locale.ROOT),
                                request.password()));
        servletRequest.getSession(true);
        servletRequest.changeSessionId();
        SecurityContext context = SecurityContextHolder.createEmptyContext();
        context.setAuthentication(authentication);
        SecurityContextHolder.setContext(context);
        contextRepository.saveContext(context, servletRequest, servletResponse);
        return Map.of("username", authentication.getName());
    }

    /**
     * Returns the username associated with the current authenticated session.
     *
     * @param principal authenticated request principal
     * @return response containing the current username
     */
    @GetMapping("/me")
    public Map<String, String> me(Principal principal) {
        return Map.of("username", principal.getName());
    }
}
